# SPDX-FileCopyrightText: Copyright (c) 2025 Aliaksei Bialiauski
# SPDX-License-Identifier: MIT

[default]
extend-ignore-identifiers-re = [
  "SXL", # language name,
  "Sxl", # language name,
  "sxl", # language name,
]
