# SPDX-FileCopyrightText: Copyright (c) 2025 Aliaksei Bialiauski
# SPDX-License-Identifier: MIT
---
name: codecov
'on':
  push:
    branches:
      - master
concurrency:
  group: codecov-${{ github.ref }}
  cancel-in-progress: true
jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mvn install "-Pjacoco"
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
