# SPDX-FileCopyrightText: Copyright (c) 2025 Aliaksei Bialiauski
# SPDX-License-Identifier: MIT
---
name: copyrights
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/copyrights-action@0.0.8
        with:
          globs: >-
            **/LICENSE.txt
            **/*.sh
            **/*.yml
            **/*.yaml
            **/*.eo
            **/*.xmir
            **/*.xml
            **/*.xsl
            **/*.xsd
            **/*.ini
            **/*.java
            **/*.g4
            **/*.properties
            **/*.toml
            **/*.groovy
