# SPDX-FileCopyrightText: Copyright (c) 2025 Aliaksei Bialiauski
# SPDX-License-Identifier: MIT
---
name: yamllint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config-file: .yamllint.yml
